version: "{branch} (#{build})"

image:
  - Visual Studio 2015

environment:
  DEBUG: 1
  WARNINGS: 1
  matrix:
    - STANDALONE: 1
      HEADER_ONLY: 1
    - STANDALONE: 1
      SEPARATE_COMPILATION: 1
    - STANDALONE: 1
      CXXLATEST: 1
    - STANDALONE: 1
      HEADER_ONLY: 1
      WIN9X: 1
    - STANDALONE: 1
      SEPARATE_COMPILATION: 1
      WIN9X: 1
    - USING_BOOST: 1
      HEADER_ONLY: 1
    - USING_BOOST: 1
      SEPARATE_COMPILATION: 1

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
    environment:
      BOOSTDIR: C:/Libraries/boost_1_63_0
    build_script:
      - PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\msys64\usr\bin;%PATH%
      - cd asio\src
      - make -f Makefile.mgw
      - make -f Makefile.mgw check

matrix:
  exclude:
    - image: Visual Studio 2013
      SEPARATE_COMPILATION: 1
    - image: Visual Studio 2013
      CXXLATEST: 1
    - image: Visual Studio 2013
      USING_BOOST: 1
    - image: Visual Studio 2015
      HEADER_ONLY: 1
    - image: Visual Studio 2015
      CXXLATEST: 1
    - image: Visual Studio 2015
      WIN9X: 1
    - image: Visual Studio 2017
      SEPARATE_COMPILATION: 1
    - image: Visual Studio 2017
      CXXLATEST: 1
    - image: Visual Studio 2017
      WIN9X: 1
    - image: Visual Studio 2017
      USING_BOOST: 1
    - image: Visual Studio 2019
      HEADER_ONLY: 1
    - image: Visual Studio 2019
      WIN9X: 1
    - image: Visual Studio 2019
      USING_BOOST: 1
